function y = data_detrending_example(x)
%DATA_DETRENDING_EXAMPLE Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 28-Jan-2016 14:02:13

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N     = 5;     % Order
    % Fstop = 0.03;  % Stopband Frequency
    % Astop = 80;    % Stopband Attenuation (dB)
    % Fs    = 10;    % Sampling Frequency
    %
    % h = fdesign.lowpass('n,fst,ast', N, Fstop, Astop, Fs);
    %
    % Hd = design(h, 'cheby2', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.99960719892872 1 1 -1.99692022380463 ...
        0.99694642262382; 1 -1.99897179681719 1 1 -1.99165613343998 ...
        0.991683388298558; 1 1 0 1 -0.994711466779526 0], ...
        'ScaleValues', [0.0666974229716918; 0.0265072692188561; ...
        0.00264426661023699; 1]);
end

y = step(Hd,x);


